# Generated by Django 3.0.5 on 2020-04-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('sex', models.CharField(max_length=20, verbose_name='性别')),
                ('sid', models.CharField(default='0', max_length=100, verbose_name='sid')),
            ],
        ),
    ]
