# Generated by Django 3.0.5 on 2020-04-26 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('text', models.TextField(verbose_name='正文')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
                ('tags', models.CharField(max_length=30, verbose_name='标签')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('is_pub', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='评论内容')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('is_pub', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app004.Article', verbose_name='标题')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
            },
        ),
    ]
